name: eventsnap-backend

x-env-file: &env-file
  - .env

x-main-api-image: &main-api-image avneesh11905/main_api:latest
x-inference-api-image: &inference-api-image avneesh11905/inference_api:gpu-latest

x-networks: &networks
  - Eventsnap-Network
  - Nginx-Network

networks:
  Eventsnap-Network:
    name: Eventsnap-Network
    driver: bridge
  Nginx-Network:
    external: true

volumes:
  rabbitmq_data:

services:
  es-rabbitmq:
    image: rabbitmq:3-management
    container_name: es-rabbitmq
    restart: unless-stopped
    env_file: *env-file
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks: *networks

  es-inference-api: 
    image: *inference-api-image
    restart: unless-stopped
    env_file: *env-file
    networks: *networks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  es-db-migration:
    image: *main-api-image
    container_name: eventsnap_migration
    command: alembic upgrade head
    env_file: *env-file
    networks: *networks

  es-main-api:
    image: *main-api-image
    env_file: *env-file
    depends_on:
      es-rabbitmq:
        condition: service_started
      es-db-migration:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: *networks

  es-celery-worker:
    image: *main-api-image
    command: celery -A infrastructure.queue.celery_app worker --loglevel=info --concurrency=4
    env_file: *env-file
    depends_on:
      es-rabbitmq:
        condition: service_started
      es-db-migration:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: *networks

  es-flower:
    image: *main-api-image
    container_name: es-flower
    command: celery -A infrastructure.queue.celery_app flower --port=5555
    env_file: *env-file
    depends_on:
      es-rabbitmq:
        condition: service_started
      es-db-migration:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: *networks
