name: eventsnap-inference

services:
  inference_api:
    image: avneesh11905/inference_api:gpu-latest
    container_name: inference_api
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: inference_nginx
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=admin@aymahajan.in
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/default.conf:ro
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - inference_api