[mypy]
ignore_missing_imports = True
plugins = pydantic.mypy

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
check_untyped_defs = True

[mypy-presentation.grpc.proto.*]
ignore_errors = True
follow_imports = skip