# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from presentation.grpc.proto import (
    inference_pb2 as presentation_dot_grpc_dot_proto_dot_inference__pb2,
)

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in presentation/grpc/proto/inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FaceInferenceStub:
    """The face inference service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFaces = channel.unary_unary(
            "/inference.FaceInference/ExtractFaces",
            request_serializer=presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            response_deserializer=presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
            _registered_method=True,
        )


class FaceInferenceServicer:
    """The face inference service."""

    def ExtractFaces(self, request, context):
        """Accepts a batch of raw image bytes, returns detected face embeddings."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FaceInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExtractFaces": grpc.unary_unary_rpc_method_handler(
            servicer.ExtractFaces,
            request_deserializer=presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceRequest.FromString,
            response_serializer=presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "inference.FaceInference", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("inference.FaceInference", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class FaceInference:
    """The face inference service."""

    @staticmethod
    def ExtractFaces(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.FaceInference/ExtractFaces",
            presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            presentation_dot_grpc_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
