name: eventsnap

x-env-file: &env-file
  - .env

x-main-api-image: &main-api-image avneesh11905/main_api:latest

x-server-port: &server-port 
  - "8003:8000"

x-networks: &networks
  - Eventsnap-Network
  - Infrastructure-Network

networks:
  Eventsnap-Network:
    driver: bridge
  Infrastructure-Network:
    external: true

services:
  es-rabbitmq:
    image: rabbitmq:3-management
    container_name: eventsnap_rabbitmq
    env_file: *env-file
    ports:
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - Eventsnap-Network

  es-db_migration:
    image: *main-api-image
    container_name: eventsnap_migration
    command: infisical run --env=prod --path=/ --path=/GCP_TOKEN -- alembic upgrade head
    env_file: *env-file
    networks: *networks
    depends_on:
      es-rabbitmq:
        condition: service_healthy

  es-main_api:
    image: *main-api-image
    ports: *server-port 
    env_file: *env-file
    depends_on:
      es-db_migration:
        condition: service_completed_successfully
      es-rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks: *networks

  es-celery_worker:
    image: *main-api-image
    command: infisical run --env=prod --path=/ --path=/GCP_TOKEN -- celery -A infrastructure.queue.celery_app worker --loglevel=info --concurrency=4
    env_file: *env-file
    depends_on:
      es-db_migration:
        condition: service_completed_successfully
      es-rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks: *networks


