"""Initial migration

Revision ID: 73990d1876b1
Revises:
Create Date: 2026-08-17 03:46:06.800574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "73990d1876b1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "event_encodings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_code", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_encodings_event_code"),
        "event_encodings",
        ["event_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_encodings_image_path"),
        "event_encodings",
        ["image_path"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_encodings_image_path"), table_name="event_encodings")
    op.drop_index(op.f("ix_event_encodings_event_code"), table_name="event_encodings")
    op.drop_table("event_encodings")
    # ### end Alembic commands ###
