"""Add ProcessedImageModel

Revision ID: d4c57e96896a
Revises: a1b2c3d4e5f6
Create Date: 2026-08-22 07:19:48.196136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd4c57e96896a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_code', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_images_event_code'), 'processed_images', ['event_code'], unique=False)
    op.create_index(op.f('ix_processed_images_image_path'), 'processed_images', ['image_path'], unique=False)
    op.create_index('uix_processed_images_event_path', 'processed_images', ['event_code', 'image_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_processed_images_event_path', table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_image_path'), table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_event_code'), table_name='processed_images')
    op.drop_table('processed_images')
    # ### end Alembic commands ###
