# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure/inference/proto/inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    "",
    "infrastructure/inference/proto/inference.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n.infrastructure/inference/proto/inference.proto\x12\tinference"d\n\x10InferenceRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x16\n\x0e\x64\x65tection_conf\x18\x02 \x01(\x02\x12\x15\n\rnms_threshold\x18\x03 \x01(\x02\x12\x11\n\tmax_faces\x18\x04 \x01(\x05"A\n\nFaceResult\x12\x0c\n\x04\x62\x62ox\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\tembedding\x18\x03 \x03(\x02"2\n\nImageFaces\x12$\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x15.inference.FaceResult";\n\x11InferenceResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.inference.ImageFaces2Z\n\rFaceInference\x12I\n\x0c\x45xtractFaces\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "infrastructure.inference.proto.inference_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INFERENCEREQUEST"]._serialized_start = 61
    _globals["_INFERENCEREQUEST"]._serialized_end = 161
    _globals["_FACERESULT"]._serialized_start = 163
    _globals["_FACERESULT"]._serialized_end = 228
    _globals["_IMAGEFACES"]._serialized_start = 230
    _globals["_IMAGEFACES"]._serialized_end = 280
    _globals["_INFERENCERESPONSE"]._serialized_start = 282
    _globals["_INFERENCERESPONSE"]._serialized_end = 341
    _globals["_FACEINFERENCE"]._serialized_start = 343
    _globals["_FACEINFERENCE"]._serialized_end = 433
# @@protoc_insertion_point(module_scope)
